services:
  sqlite:
    image: alpine
    container_name: sqlite
    command: [ "sh", "-c", "apk add --no-cache sqlite && touch /data/task.db && tail -f /dev/null" ]
    volumes:
      - ./sqlite-data:/data
    restart: always